title: Askabout
description: Archive of public surveys using Aska.
theme: just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/favicon_high-resolution.png"
favicon_ico: "/assets/images/favicon.ico"

url: https://Aska-systems.github.io/Askabout

# aux_links:
#   Aska Website: https://aska.systems

footer_content: "&copy; Aska Intelligence LLC"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

collections:
  posts:
    output: true
    permalink: /:collection/:title

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "posts" collection
    posts:
      # Give the collection a name
      name: Posts
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
